/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include <string.h>
#include <stdlib.h>
#include "user_led.h"
#include "motor.h"
#include "intadc.h"
#include "LUT.h"
#include "UserInputButton.h"
#include "filter.h"
#include "system_stm32f4xx.h"
#include "timebase.h"
#include "DebugPort.h"

/**
 * @brief PWM Monitor - STM32F401 PWM Signal Monitoring with ADC Feedback
 * 
 * This application monitors PWM signals and uses ADC feedback to check if the voltage
 * is within specified thresholds. It controls LED indicators based on voltage levels
 * and provides UART debug output for monitoring system status.
 * 
 * Components:
 * - PWM input monitoring on TIM2 CH2 (PA1)
 * - ADC feedback on PA0 (0-3.3V)
 * - User button on PC13 (active low)
 * - Status indicator LED on PA5
 * - UART debug output on USART2 (PA2/PA3)
 * - SysTick timer for periodic callbacks
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Global Variables */
float adc_filtered;         /**< Filtered ADC voltage reading (0-3.3V) */
int errorFlag = 0;          /**< Error flag: 1 if ADC reading exceeds limits */
int duty_cycle = 0;         /**< Motor PWM duty cycle (0-10) */
int allow_adc_setting = 0;  /**< Flag to skip error check after duty cycle change */
int seconds = 0;            /**< Seconds counter for debug output */



/**
 * @brief Callback function called every 1 second to send debug data over UART.
 * Sends current ADC voltage, motor duty cycle, and error status.
 */
void SecondIncrementer(){
	seconds++;

	int formatted_voltage = (adc_filtered)*100;
	int formatted_LUT_value = LUT_ADC_vals[duty_cycle]*100;

	char tosend[200] ;
	sprintf(tosend,"%d : ADC Voltage %d Duty Cycle %d Upper Voltage Limit %d Error Flag %d\n",
			seconds,formatted_voltage,duty_cycle,formatted_LUT_value,errorFlag);

	DebugPortSend(tosend,strlen(tosend));
}


/**
 * @brief Callback function called every 200ms to check user button input.
 * Cycles motor speed through duty cycle values 0-10. Sets flag to skip
 * error checking for one cycle after speed change.
 */
void UserButtonHandler(){
	int button_val;
	button_val = UserButtonRead();
	/* Check if button pressed (active low) */
	if(button_val == 0) {

		/* Cycle duty cycle from 0-10 */
		if(duty_cycle >= 10)
			duty_cycle = 0;
		else
			duty_cycle += 1;

		MotorSpeedUpdate(duty_cycle);
		allow_adc_setting = 1;  /* Skip error check for one cycle */


	}
}

/**
 * @brief Callback function called every 100ms to read and filter ADC value.
 * Reads raw ADC, converts to voltage, and applies low-pass filter.
 */
void ADCReadHandler(){
	int adcVal = 0;
	float adc_volt = 0;

	adcVal = readAdc();
	adc_volt = ConvertToVoltage(adcVal);
	adc_filtered = mv_filter(adc_volt);

}

/**
 * @brief Callback function called every 1 second to check ADC feedback against LUT.
 * 
 * Compares the filtered ADC voltage against the lookup table value for the
 * current duty cycle +/- 0.2V. Sets error flag and lights LED if out of range.
 * Skips check for one cycle after duty cycle change to allow settling time.
 */
void ErrorCheckerHandler(){
	/* Skip error checking for one cycle after duty cycle change (settling time) */
	if(allow_adc_setting == 1)
	{
		allow_adc_setting = 0;
		return;
	}

	/* Check if ADC reading is outside +/- 0.2V tolerance band */
	if((adc_filtered > (LUT_ADC_vals[duty_cycle] + 0.2)) ||
		(adc_filtered < (LUT_ADC_vals[duty_cycle] - 0.2)))
	{
		errorFlag = 1;
		UserLedUpdate(1);  /* Turn on error LED */
	}


}

/**
 * @brief Main entry point. Initializes all peripherals and starts main loop.
 * 
 * Initialization sequence:
 * 1. System clock and core clock updates
 * 2. GPIO peripherals (button, LED, motor, ADC, UART)
 * 3. Timer peripherals (PWM for motor, SysTick for callbacks)
 * 
 * Periodic callbacks registered:
 * - 100ms: Read and filter ADC value (ADCReadHandler)
 * - 200ms: Check user button input (UserButtonHandler)
 * - 1000ms: Check error conditions (ErrorCheckerHandler)
 * - 1000ms: Send debug data over UART (SecondIncrementer)
 */
int main(void)
{
	/* Initialize system clocks */
	SystemInit();
	SystemCoreClockUpdate();

	/* Initialize peripherals */
	UserButtonInit();   /* PC13 input for speed control */
	UserLedInit();      /* PA5 output for error indication */
	MotorInt();         /* PA1 PWM timer setup */
	IntADCInit();       /* PA0 ADC initialization */
	TimeBaseInit();     /* SysTick timer setup */
	DebugPortInit();    /* UART2 for debug output */

	/* Start motor and ADC */
	MotorStart();       /* Start PWM on TIM2 CH2 */
	IntADCStart();      /* Enable ADC1 */

	/* Register periodic callback functions with SysTick */
	TimeBaseRegisterCallback(1000, SecondIncrementer);    /* 1Hz debug output */
	TimeBaseRegisterCallback(200,  UserButtonHandler);    /* 5Hz button check */
	TimeBaseRegisterCallback(100,  ADCReadHandler);       /* 10Hz ADC sampling */
	TimeBaseRegisterCallback(1000, ErrorCheckerHandler);  /* 1Hz error check */

	/* Main loop - all work done in interrupt callbacks */
	while(1) {
		/* Idle - callbacks execute in SysTick interrupt */
	}

	return 0;
}

